import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.learnwebdriverio.com/register');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('alyonkalozovaya@gmail.com');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Username' }).press('End');
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Username' }).fill('alyonkalozovaya');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('alyonkalozovaya@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456qwert!')
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Password' }).fill('123456qwert!');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByText('A place to share your').click();
  await page.getByRole('link', { name: 'alyonkalozovaya' }).click();
  await page.getByRole('link', { name: 'Favorited Articles' }).click();
  await page.getByRole('link', { name: '  Settings' }).click();
  await page.getByRole('button', { name: 'Or click here to logout.' }).click();
  await expect(page.getByRole('link', { name: 'Home' })).toBeVisible();
  await page.getByRole('link', { name: ' Sign in' }).click();');
  await page.getByRole('button', { name: 'Sign up' }).click();
  await page.getByRole('heading', { name: 'conduit' }).click();
  await page.getByText('A place to share your').click();
  await expect(page.locator('#app')).toContainText('alyonkalozovaya');
  await expect(page.locator('#app')).toContainText('conduit');
  await expect(page.locator('#app')).toContainText('A place to share your knowledge.');
});